name: Open in YouTube
version: 0.1.1
description: Adds a button to YouTube Music and Shorts to open the video in YouTube
icon: favicon:youtube.com
match:
  - https://music.youtube.com/watch?v=*
  - https://www.youtube.com/*
run-at: document-end
grant:
  - GM_openInTab
  - GM_addStyle
